version: "3.8"
services:
  
  mongodb:
      container_name: mongo_fruitvision
      image: mongo:latest
      restart: always
      ports:
        - "27018:27017"
      networks:
        - fruitvision-network
      environment:
        MONGO_INITDB_ROOT_USERNAME: "mongo"
        MONGO_INITDB_ROOT_PASSWORD: "fruitvision"
        # MONGO_URI: mongodb://mongo:fruitvision@localhost:27017/
      volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb

  mongo-express:
      image: mongo-express:latest
      container_name: mongo-express_fruitvision
      restart: always
      ports:
        - 8081:8081
      networks:
        - fruitvision-network
      environment:    
        ME_CONFIG_SITE_BASEURL: "/mongodb/"
        ME_CONFIG_MONGODB_URL: "mongodb://mongo:fruitvision@mongodb:27017/"      
        ME_CONFIG_MONGODB_SERVER: "mongodb"
        ME_CONFIG_MONGODB_ADMINUSERNAME: "mongo"
        ME_CONFIG_MONGODB_ADMINPASSWORD: "fruitvision"
      depends_on:
        - mongodb
    
  backend:
      image: hiba25/backend
      container_name: backend_container
      ports:
        - "5000:5000"
      environment:
        DB_URI: "mongodb://mongo:fruitvision@mongodb:27017/"
      depends_on:
        - mongo-express
      networks:
        - fruitvision-network
  
networks:
  fruitvision-network:
    driver: bridge

volumes:
  MONGO_DATA:
    name: MONGO_DATA
  MONGO_CONFIG:
    name: MONGO_CONFIG
  # modele:
  #     image: hiba25/modele
  #     container_name: modele_fruit_container
  #     ports:
  #       - "8000:8000"
  #     environment:
  #       MODEL_PATH: "/app/model_path/model_final.pth"
  #       BASE_URL: "http://192.168.146.95:8000"
  #     networks:
  #       - supspace-network
