# Utiliser une image officielle Node.js comme image de base
FROM node:18.17.1

# Définir le répertoire de travail dans le conteneur
WORKDIR /usr/src/app

# Copier le fichier package.json et package-lock.json (si disponible)
COPY package.json ./
COPY package-lock.json ./

# Installer les dépendances du projet
RUN npm install

# Copier les autres fichiers du projet dans le conteneur
COPY . .

# Exposer le port sur lequel votre app tourne
EXPOSE 5000

# Commande pour démarrer votre application
CMD ["node", "server.js"]